--- #YAML:1.0
name: CGI-Application-Search
version: 0.08
author:
  - Michael Peters <mpeters@plusthree.com>
abstract: Base class for CGI::App Swish-e site engines
license: perl
requires:
  CGI::Application: 3.2
  CGI::Application::Plugin::AnyTemplate: 0
  CGI::Application::Plugin::HTMLPrototype: 0
  Data::Page: 1
  File::Spec: 0
  File::Spec::Functions: 0
  HTML::FillInForm: 1.04
  HTML::HiLiter: 0.12
  Number::Format: 0
  POSIX: 0
  SWISH::API: 0.01
  Text::Context: 3.5
  Time::HiRes: 0
  Time::Piece: 0
  perl: 5.6.1
provides:
  CGI::Application::Search:
    file: lib/CGI/Application/Search.pm
    version: 0.08
generated_by: Module::Build version 0.2611
