---
name: CGI-Application-Search
version: 1.10
author:
  - 'Michael Peters <mpeters@plusthree.com>'
abstract: Base class for CGI::App Swish-e site engines
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Class: 0
  Test::LongString: 0
requires:
  CGI::Application: 4
  CGI::Application::Plugin::AnyTemplate: 0
  Capture::Tiny: 0.06
  Cwd: 0
  Data::Page: 1
  Encode: 0
  File::Slurp: 9999.13
  File::Spec: 0
  File::Spec::Functions: 0
  HTML::FillInForm: 1.04
  Number::Format: 0
  POSIX: 0
  SWISH::API: 0.04
  Search::Tools::HiLiter: 0.12
  Text::Context: 3.5
  Time::HiRes: 0
  Time::Piece: 0
  Unicode::Normalize: 0
  perl: v5.6.1
configure_requires:
  Module::Build: 0.35
provides:
  CGI::Application::Search:
    file: lib/CGI/Application/Search.pm
    version: 1.10
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
