--- #YAML:1.0
name: CGI-Application-Search
version: 1.00
author:
  - Michael Peters <mpeters@plusthree.com>
abstract: Base class for CGI::App Swish-e site engines
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
